@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods
hide interface attributes

skinparam class {
    backgroundColor<<enum>> Orange
    backgroundColor<<interface>> LightGreen
    backgroundColor<<abstract>> LightBlue
    backgroundColor LightGray
}

package views
{
  class MenuWindow{}
  class GameWindow implements .models.GameObserver
  {
    -_attemptIndex : Integer
    -_isNumeric : Boolean
  }
  class EndWindow{}
}

package controllers
{
  class GameController
  {
    -_username : String
    -_nbRounds : Integer
    -_nbColors : Integer
    -_nbColorsInCombination : Integer
    -_nbAttempts : Integer
  }
}

package models
{
  class Game
  {
    -_currentRound : Integer
  }

  class Round
  {
    -_isWon : Boolean
  }

  class Attempt{}

  class Combination
  {
    _nbColorsInCombination : Integer
  }

  class Solution extends Combination{}
  interface GameObserver{}
  enum Clue{}
  enum GameMode{}
  enum PawnColor{}
}

class MasterMindApp
{
}

Game *-> "3.d.5 \n -_rounds" Round : > <<owns>>
Game *-> "1.u.* \n -_observers" GameObserver : > <<owns>>
Game ..> GameMode : > <<uses>>
Game ..> Combination : > <<uses>>

Round *--> "1 \n -_solution" Solution : > <<owns>>
Round *-d-> "10..12 \n -_attempts" Attempt : > <<owns>>
Round *--> "1 \n -_gamemod" GameMode : > <<owns>> <!-- Adjusted layout here -->
Round ..> Combination : > <<uses>>
Round ..> Clue : > <<uses>>

Attempt *-> "1\n- _combinationSubmited" Combination : > <<owns>>
Attempt *-> "1\n- _clues" Clue : > <<owns>>

Combination o-> "4..6\n # _PAWNS" PawnColor : > <<contains>>

Solution .d.> PawnColor : > <<uses>>
Solution .d.> Clue : > <<uses>>

GameController *-d-> "1 \n -_game" Game : > <<owns>>
GameController .u.> GameWindow : > <<create>>
GameController .u.> EndWindow : > <<create>>
GameController .d.> GameMode : > <<uses>>

MenuWindow .d.> GameController : > <<uses>>
MenuWindow .d.> GameMode : > <<uses>>

GameWindow .d.> GameController : > <<uses>>
GameWindow .d.> GameMode : > <<uses>>

EndWindow .d.> GameController : > <<uses>>

MasterMindApp .d..> GameController : > <<create>>
MasterMindApp .d..> MenuWindow : > <<create>>
@enduml
