@startuml

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods
hide interface attributes

/'
Main :
    - MasterMindApp

Views :
    Classes :
        - MenuWindowView
        - SettingsWindowView
        - GameWindowView
        - EndWindowView
    Interfaces :
        /
    Enums :
        /

Controllers :
    Classes :
        - MasterMindController
        - GameController
    Interfaces :
        /
    Enums :
        /

Models :
    Classes
        - MasterMind
        - Game
        - Round
        - Combination
        - Solution
        - DisplayCluesFactory
        - DisplayCluesClassic
        - DisplayCluesEasy
        - DisplayCluesNumeric
    Interfaces
        - DisplayCluesStrategy
        - MasterMindObserver
        - GameObserver
        - RoundObserver
    Enums
        - PawnColor
        - GameMode
        - Clue
'/

class MasterMindApp {
    - main(args: String[])
}

package models {
    class MasterMind {}
    class Game {
        - {static} _nbRounds: Integer
        - _currentRoundNb: Integer
        + Game()
        + {static} setNbRounds(nbRounds: Integer)
        'Pas encore utilisé, à supprimer ?
        + getNbRounds(): Integer
        - startGame()
        + nextRound()
        - isGameOver(): Boolean
        - launchNextRound()
        - endGame()
    }
    class Round {
        - {static} _nbAttempts: Integer
        - _currentAttemptNb: Integer
        + Round()
        + {static} setNbAttempts(nbAttempts: Integer)
        'Pas encore utilisé, à supprimer ?
        + getNbAttempts(): Integer
        - startRound()
        - nextAttempt()
        - isRoundOver(): Boolean
        - launchNextAttempt()
        + submitCombination(combination: Combination)
        - endRound()
    }
    class Combination {
        - {static} _nbColorsInCombination: Integer
        # Combination()
        + Combination(pawns : PawnColor[])
        + {static} setNbColorsInCombination(nbColorsInCombination: Integer)
        + getNbColorsInCombination(): Integer
    }
    class Solution extends Combination {
        + Solution()
        + generateSolution()
        + compareWithCombination(combination: Combination): Clue[]
        + isInSolution(pawnColor: PawnColor): Boolean
        + isSolutionFound(clues : Clue[]): Boolean
    }
    class DisplayCluesFactory {}
    class DisplayCluesClassic implements DisplayCluesStrategy {}
    class DisplayCluesEasy implements DisplayCluesStrategy {}
    class DisplayCluesNumeric implements DisplayCluesStrategy {}

    interface DisplayCluesStrategy <<interface>> {
    }
    interface MasterMindObserver <<interface>> {}
    interface GameObserver <<interface>> {}
    interface RoundObserver <<interface>> {}

    'Baisser le nombre de couleurs à 9 (8 + 1 pour le vide), ou 8 (rien pour le vide)
    enum PawnColor <<enum>> {
        RED
        GREEN
        BLUE
        YELLOW
        ORANGE
        PINK
        LIGHT_GRAY
        MAGENTA
    }
    enum GameMode <<enum>> {
        CLASSIC
        EASY
        NUMERIC
    }
    enum Clue <<enum>> {
        WELL_PLACED
        MISPLACED
        WRONG
    }
}

'Relations

'Main



'Models
'MasterMind


'Game
Game ..> Round : > <<uses>>

'Round
Round *--> "1\n- _solution" Solution : > <<owns>>
Round ..> Combination : > <<uses>>
Round ..> Clue : > <<uses>>

'Combination
Combination o--> "*\n # _pawns" PawnColor : > <<contains>>

'Solution
Solution ..> PawnColor : > <<uses>>
Solution ..> Clue : > <<uses>>

'Clue

'DisplayCluesFactory


'DisplayCluesClassic


'DisplayCluesEasy


'DisplayCluesNumeric


'DisplayCluesStrategy


'MasterMindObserver


'GameObserver


'RoundObserver


'PawnColor


'GameMode

@enduml